<?xml version="1.0" encoding="utf-8"?><Database Name="Study" Class="StudyDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Study;Integrated Security=True" SettingsObjectName="Strudy_ado_2.Properties.Settings" SettingsPropertyName="StudyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>