//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int itemId { get; set; }
        public string itemTitle { get; set; }
        public string creator { get; set; }
        public string info { get; set; }
        public int categoryId { get; set; }
    }
}
