<?xml version="1.0" encoding="utf-8"?><Database Name="shop1" Class="ShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-CVQ36AP;Initial Catalog=shop1;Integrated Security=True" SettingsObjectName="Shop_linq.Properties.Settings" SettingsPropertyName="shop1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Articles" Member="Articles">
    <Type Name="Article">
      <Column Name="articleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="articleTitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Article_OrderDetail" Member="OrderDetails" ThisKey="articleId" OtherKey="articleId" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="detailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="articleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Article_OrderDetail" Member="Article" ThisKey="articleId" OtherKey="articleId" Type="Article" IsForeignKey="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="orderId" OtherKey="orderId" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="orderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderNumber" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="orderDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="orderId" OtherKey="orderId" Type="OrderDetail" />
    </Type>
  </Table>
</Database>